# Generated by Django 6.0.5 on 2026-05-26 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_emissionrecord_analyst_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasource',
            old_name='file_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emissions.datasource'),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='normalized_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='normalized_unit',
            field=models.CharField(default='Liters', max_length=50),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emissions.organization'),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='record_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='scope',
            field=models.CharField(default='SCOPE_1', max_length=50),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='unit',
            field=models.CharField(default='Liters', max_length=50),
        ),
    ]
