# Generated by Django 6.0.5 on 2026-05-27 06:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_rename_file_name_datasource_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='name',
        ),
        migrations.AddField(
            model_name='datasource',
            name='file_name',
            field=models.CharField(default='uploaded.csv', max_length=255),
        ),
        migrations.AddField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel')], default='SAP', max_length=20),
        ),
        migrations.AddField(
            model_name='datasource',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
