# Generated by Django 6.0.5 on 2026-05-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0004_remove_datasource_name_datasource_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
